---
# Print some debug, make directories, and initialize
- name: Print debug
  debug:
    msg: "run_diagnostics: {{ run_diagnostics }}, load_firmware: {{ load_firmware }}, update_firmware: {{ update_firmware }}
          Copyng files to {{ fw_dir }} on DGX nodes, running container: {{ firmware_update_repo }}, tag: {{ firmware_update_tag }}"
- name: Make firmware dir
  file:
    path: "{{ fw_dir }}"
    state: directory
    mode: '0755'
- name: Copy Wrapper Script
  copy:
    src: parse_manifest.py
    dest: "{{ fw_dir }}/parse_manifest.py"
    mode: '0644'
    force: yes

- block:
  # Run some pre-flight diagnostics pre-firmware update in case things go wrong
  - include: run-diagnostics.yml
    vars:
      run_diagnostics_type: '-pre-check'
    when:
      - run_diagnostics
      - load_firmware or update_firmware

  # Verify the local container exists, then copy it over if necessary and verify it is loaded into Docker
  - include: load-image.yml
    when: load_firmware

  # Update the FW and reboot if necessary
  - include: update-firmware.yml
    when: update_firmware

  # Run post-flight diagnostics
  - include: run-diagnostics.yml
    vars:
      run_diagnostics_type: '-post-check'
    when: run_diagnostics

  always:
  - include: transfer-logs.yml # In case of failure, this will pull whatever logs were captured; in case of success it will pull the later logs and some pre-flight checks may be overwritten

# Clean up the loaded images and copied files
- include: clean.yml
  when: clean_fw
