---
- name: Starting firmware update step
  debug:
    msg: "Starting now"

- include: check-firmware.yml

- block:
  - name: Stop NVSM_CORE before updating # TODO: BUG: Due to bug in current container workflow
    service:
      name: nvsm-core
      state: stopped

  - name: Check if force update requested
    set_fact:
      force_parameter: "{{ '-f' if force_update else '' }}"

  - name: Update firmware if required
    shell: "docker run --rm -ti --privileged -v /:/hostfs -e NVSM_MODE=1 {{ firmware_update_repo }}:{{ firmware_update_tag }} set_flags AUTO=1 update_fw {{ target_fw }} {{ force_parameter }} > {{ fw_dir }}/fw-update.json" 

  - name: "Parse FW Update output"
    command: "python3 {{ fw_dir }}/parse_manifest.py parse_update_json {{ fw_dir }}/fw-update.json"
    register: update_output
  - name: To json
    set_fact:
      fw_update_json: "{{ update_output.stdout }}"
  - name: Register reboot as required
    set_fact:
       reboot_required: "{{ true if 'rebootHard\": true' in fw_update_json else false }}"

  when:
    - firmware_needs_upgrade | default(false)

- name: Reboot if necessary
  shell: sleep 2 && /sbin/shutdown -r now "Reboot required"
  async: 1
  poll: 0
  when:
    - reboot_required | default(false)

- name: Wait for server to reboot (if required)
  wait_for_connection:
    delay=15
    timeout={{ reboot_timeout }}

- name: Print Debug
  debug:
    msg: Host is online

- name: Start NVSM_CORE after completion  # TODO: BUG: Due to bug in current container workflow
  service:
    name: nvsm-core
    state: started

- include: verify-firmware.yml
